<!DOCTYPE html>
<html lang="ru">
<head>
<meta charset="UTF-8" />
<title>Кнопка Любви</title>
</head>
<body>

<button id="loveButton">ТЫК</button>
<p id="message"></p>

<script>
  document.getElementById('loveButton').addEventListener('click', function() {
    document.getElementById('message').textContent = 'я тебя люблю❤️';
  });
</script>

</body>
</html>
